spring:
  application:
    name: MusicBox
  datasource:
    url: jdbc:h2:file:C:\h2\musicBox
    username: tadeja
    password: tadeja
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true